# -*- coding: utf-8 -*-
"""Ejercicio Mineria

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpmZtHTsE3KW7TIte3EcZfEnjW_bgv9J
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

datos = {'naranjas':[2,3,1,0],'manzanas':[0,3,7,2]}
compras = pd.DataFrame(datos)

url = 'https://raw.githubusercontent.com/ManarOmar/New-York-Airbnb-2019/master/AB_NYC_2019.csv'
data= pd.read_csv(url)

data.head()

data.describe()

columnas = ['price','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365']

data[columnas].describe()

numericas = data[columnas]
numericas = numericas.fillna(numericas.mean())
print (numericas)

data.isnull().sum()
sin_resenas = (data['number_of_reviews']) == 0
print(str('Anuncios sin reseñas'), sin_resenas.sum())

data.hist(bins = 20, figsize = (10,6))
plt.tight_layout()
plt.show()

data['neighbourhood'].value_counts()

data['neighbourhood_group'].value_counts()

data['room_type'].value_counts()

media = data['reviews_per_month'].mean()
print('Media de reviews_per_month', round(media,2))

data['reviews_per_month'] = data['reviews_per_month'].fillna(0)
data['reviews_per_month'].isnull().sum()
print(data['reviews_per_month'])

data['row_mean'] = data['reviews_per_month'].fillna(media)
data['row_na'] = data['reviews_per_month'].fillna(0)
data.describe()

numericas = data.select_dtypes(include=np.number)
numericas

data.boxplot(column = 'price',figsize = (8,10))
plt.ylabel("precio por noche (USD)")
plt.show()

precio_minimo = min(data['price'])
precio_maximo = 450
print('Precio minimo', precio_minimo)
print('Precio maximo', precio_maximo)
datos_limpios = data[(data['price'] > precio_minimo) & (data['price'] <= precio_maximo)].copy()
print('Antes:' , len(data), 'Anuncios')
print('Despues: ' , len(datos_limpios) , 'anuncios')

media_nueva = round(datos_limpios['price'].mean(),2)
print('La nueva media es', media_nueva)

datos_limpios.boxplot(column = 'price',figsize = (8,10))
plt.ylabel("precio por noche (USD)")
plt.show()

datos_limpios['price'].hist(bins=50, figsize=(10,8))
plt.xlabel('Precio por Noche (USD)')
plt.ylabel('Anuncios')
plt.title('Distribucion del precio')
plt.show()

corte_economico = 80
corte_medio = 200

def categoria_precio(precio):
  if precio <= corte_economico:
    return 'economico'
  elif precio <= corte_medio:
    return 'medio'
  else:
    return 'premium'

categoria_precio(50)

datos_limpios['categoria'] = datos_limpios['price'].apply(categoria_precio)
datos_limpios['categoria'].value_counts()

datos_limpios.groupby('neighbourhood_group')['price'].agg(['count','mean','median'])

datos_limpios.groupby(['neighbourhood_group','room_type'])['price'].median().unstack()

datos_limpios.corr(numeric_only=True)

!pip install dtale
import dtale
import dtale.app as dtale_app

dtale_app.USE_COLAB = True

dtale.show(datos)